[build]
  publish = "public"
  command = "npm run build"
  functions = "lambda"
[build.environment]
  node ./scripts/create-env.js &&
  NODE_VERSION = "12"
  YARN_VERSION = "1.22.4"
  YARN_FLAGS = "--no-ignore-optional"
